import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeDefault from "../components/HomeDefault";
import React, {useState} from 'react';
import Game from '../components/Game';

export default function Home() {
  const [activeGame, setactiveGame] = useState(null)
  return (
    <div className={styles.container}>
      <Head>
        <title>Parchís educativo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='container-title'>
          <h1 >
            Bienvenido a  <span >Parchis</span>
          </h1>
        </div>
        {!activeGame
        ?(
          <HomeDefault setactiveGame={setactiveGame}/>
        ) :
        (<Game game={activeGame} setactiveGame={setactiveGame}/>)}
        
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
